# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spirlctl < Formula
  desc "SPIRL Control CLI"
  homepage "https://www.spirl.com/"
  version "0.15.1-dirty"
  depends_on :macos

  on_arm do
    url "https://spirl-releases.s3.us-west-2.amazonaws.com/spirlctl/v0.15.1-dirty/spirlctl-v0.15.1-dirty-darwin-arm64.tar.gz"
    sha256 "a0d68460cb7b121652ab19079cdbd11cefebe119e30918088f2c0bad28b6182b"

    def install
      bin.install "spirlctl"
    end
  end
end
