# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spirlctl < Formula
  desc "SPIRL CLI"
  homepage "https://www.spirl.com/"
  version "0.18.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://spirl-releases.s3.us-west-2.amazonaws.com/spirlctl/v0.18.0/spirlctl-v0.18.0-darwin-amd64.tar.gz"
      sha256 "3fd76718dcc54ebacc162419c10f26b7bdf3dcc6938e5a027842783d59bb2d1f"

      def install
        bin.install "spirlctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://spirl-releases.s3.us-west-2.amazonaws.com/spirlctl/v0.18.0/spirlctl-v0.18.0-darwin-arm64.tar.gz"
      sha256 "16e1729f6319f4df97577d4cae8e0e82772b10ea018f58a412e7b8556dce7946"

      def install
        bin.install "spirlctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://spirl-releases.s3.us-west-2.amazonaws.com/spirlctl/v0.18.0/spirlctl-v0.18.0-linux-amd64.tar.gz"
        sha256 "3a0abbc30cd98bbc3d3731b975fafb07aee9fddb4401b400139f91415c560e63"

        def install
          bin.install "spirlctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://spirl-releases.s3.us-west-2.amazonaws.com/spirlctl/v0.18.0/spirlctl-v0.18.0-linux-arm64.tar.gz"
        sha256 "ba76ff026b65459ccf019b9b089fa68ca47cd6c5980134866fed7113755a8ce9"

        def install
          bin.install "spirlctl"
        end
      end
    end
  end
end
