# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spirlctl < Formula
  desc "SPIRL Control CLI"
  homepage "https://www.spirl.com/"
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://spirl-releases.s3.us-west-2.amazonaws.com/spirlctl/v0.0.0/spirlctl-v0.0.0-darwin-amd64.tar.gz"
      sha256 "cdb3440ec2b635a575a6259d41737ec1af19933c5996e5da508f72e9d7393dad"

      def install
        bin.install "spirlctl"
      end
    end
    on_arm do
      url "https://spirl-releases.s3.us-west-2.amazonaws.com/spirlctl/v0.0.0/spirlctl-v0.0.0-darwin-arm64.tar.gz"
      sha256 "eaab6f41b5c1b2429a8ffeacafd06b5bdbecc590c70b0f4efa76c29efd431dca"

      def install
        bin.install "spirlctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://spirl-releases.s3.us-west-2.amazonaws.com/spirlctl/v0.0.0/spirlctl-v0.0.0-linux-amd64.tar.gz"
        sha256 "c1286828c44d7a8630e587ccf1bb1105c02413cec740159b801b1cbaf48f0e3b"

        def install
          bin.install "spirlctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://spirl-releases.s3.us-west-2.amazonaws.com/spirlctl/v0.0.0/spirlctl-v0.0.0-linux-arm64.tar.gz"
        sha256 "e80dc20d48df8cec025db688833c44279a1b1b0818e408b3922adbd8d78521d8"

        def install
          bin.install "spirlctl"
        end
      end
    end
  end
end
